<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.26" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.3" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
      <PackageReference Include="Refit" Version="10.1.6" />
      <PackageReference Include="Refit.HttpClientFactory" Version="10.1.6" />
      <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BackgroundRateService.Domain\BackgroundRateService.Domain.csproj" />
        <ProjectReference Include="..\BackgroundRateService.Application\BackgroundRateService.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="External\Models\" />
    </ItemGroup>

</Project>
